### ISSUE TITLE
[DOC] Add landing pages for overviews

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#10]
Add (and improve) landing pages for each main diataxis category. 

* [x] #19
* [x] #20
* [x] #21
* [x] #22
* [x] #23
* [x] #24

[Upgraded content notion doc](https://www.notion.so/quansightlabs/bc532b6549734ec198454f44f8578188?v=aad438eb66774c6f8481dca61677825d)

**Comment by pavithraes** [comment]
Something like: https://www.gatsbyjs.com/docs/how-to/

**Comment by pavithraes** [comment]
Since we have overview pages for all the sections now, and we're tracking improvements in #183, I'll close this issue as complete. :)
