### ISSUE TITLE
[DOC] - Update advanced-settings discussion in Getting Started

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#102]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

[Original comment/source](https://github.com/nebari-dev/nebari-docs/pull/45#discussion_r906398850)

>This installation guide provides the basic needs to install and deploy Nebari for the first time and assumes the user is already familiar with the [Conda](https://docs.conda.io/projects/conda/en/latest/) and [Python packaging](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-packages) ecosystems. If you are already familiar to Nebari and would like to check the advance configuration, feel free to skip to "advanced-settings" section.

### Steps to Resolve this Issue

add some docs

**Comment by viniciusdc** [comment]
This is currently blocked until https://github.com/nebari-dev/nebari-docs/pull/115 is merged (or we have an advanced-settings page to link to)
