### ISSUE TITLE
[DOC] - Add next steps to getting started

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari-docs#109]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

There is a need to include some next steps instructions to the end user once Nebari is fully installed, directing the user on how to access Nebari and use its services

### Steps to Resolve this Issue

1. Add end note to each cloud provider with proper link and information
2.
3.
...

**Comment by kcpevey** [comment]
done.
