### ISSUE TITLE
[DOC] Nebari architecture and conceptual guide

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#11]
Add documentation page (md) titled `Nebari architecture and conceptual guide`

👉  [notion page](https://www.notion.so/quansightlabs/Nebari-architecture-and-conceptual-guide-05a50bd693ae4e98b166833114896faa)

Examples in other documentation sites
- https://kubernetes.io/docs/concepts/
- https://www.kubeflow.org/docs/started/architecture/

**Comment by kcpevey** [comment]
Related:
#27 #28 #29 #30 #31

**Comment by costrouc** [comment]
See PR https://github.com/nebari-dev/nebari/pull/59
