### ISSUE TITLE
Create a QHub -  CLI diagram

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docs#111]

**Comment by iameskild** [comment]
![QHub CLI - current state 2022_8_8](https://user-images.githubusercontent.com/42120229/183530202-f345f4fd-ad15-4f42-ae8c-a9e4e2737f1e.jpeg)

cc @asmijafar20

**Comment by asmijafar20** [comment]
I can see we added more flags to `qhub init` command. Do we need to change the steps which we already have defined in our docs?

**Comment by viniciusdc** [comment]
Hi, @asmijafar20. All the flags and commands in the diagram above are already part of Nebari. They are not necessary for a basic deployment (as we have default values for them) but can also be passed for customization once the user already understands its meaning. -- currently on nebari.dev we don't have a page explanation of those yet

**Comment by asmijafar20** [comment]
> Hi, @asmijafar20. All the flags and commands in the diagram above are already part of Nebari. They are not necessary for a basic deployment (as we have default values for them) but can also be passed for customization once the user already understands its meaning. -- currently on nebari.dev we don't have a page explanation of those yet

Okay. So I think we could have a `help` command where we can also define these flags and add their other customizations. Let me know what do you think.

**Comment by viniciusdc** [comment]
> > Hi, @asmijafar20. All the flags and commands in the diagram above are already part of Nebari. They are not necessary for a basic deployment (as we have default values for them) but can also be passed for customization once the user already understands its meaning. -- currently on nebari.dev we don't have a page explanation of those yet
> 
> Okay. So I think we could have a `help` command where we can also define these flags and add their other customizations. Let me know what do you think.

Yup, also, I think drafting a Help message and adding those commands would be a good start on using Typer

**Comment by trallard** [comment]
We definitely need a `help` command

**Comment by asmijafar20** [comment]
Got an idea of having a `setup command` like `qhub setup (any cloud provider)` and asks permissions you need to enable for qhub while creating JSON file or exporting cloud provider credentials and project id in this command. And if user didn't setup the cloud provider then it shows the message with the [docs link ](https://www.nebari.dev/how-tos/nebari-gcp#set-up-the-gcloud-cli) on how of do it. Like this 
![Screenshot from 2022-08-07 00-19-32](https://user-images.githubusercontent.com/47150162/183896429-9ee34572-a61c-4b98-ab1d-938492f972c7.png)
Let me how it sound to you folks. @viniciusdc @trallard @iameskild

**Comment by iameskild** [comment]
When we finish our work on the new CLI, we might want to create another such diagram and add it to the docs. For now, I believe this issue can be closed. @trallard @asmijafar20 let me know if you feel otherwise 👍
