### ISSUE TITLE
[DOC] Github link should point to code repo

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#114]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

The github link in the top right of the nebari docs currently points to the docs repo. It should point to the code repo

### Steps to Resolve this Issue

Fix it in docusaurus.

**Comment by kcpevey** [comment]
Currently blocked until the code repo gets migrated.

**Comment by trallard** [comment]
Why should it point to the nebari repo instead of the docs repo? 
 More than likely folks will find an issue with the docs or missing information and want to head there not to the nebari development repository

**Comment by kcpevey** [comment]
I think its pretty standard when you see the github logo in a docs repo, you expect it to the take you to the code repo, not the docs. Just checked and this is true for numpy and scipy. I think the button is there so that people can quickly jump over to look at the codebase for more in depth look. That is my interpretation.

**Comment by pavithraes** [comment]
Most projects have their docs in the codebase itself, under a `doc(s)` directory, so the link works both as a code and docs reference. This is not the case for us, so we need to be careful here.

Our `nebari-dev/nebari` codebase has a "docs" folder (with the old docs) which will certainly confuse new users. So right now, if we have to choose, linking to the docs repo is the safer idea.

Some options:
- The GitHub logo can link to our organization page `github.com/nebari-dev`, and users can navigate to whichever repo they want
- We can have separate, explicit, links for both the codebase and docs repo in the navbar, perhaps as a dropdown (I'd personally prefer this) 

We can also consider a discussion about moving the docs into the codebase in the upcoming Nebari standup.

`conda` is the only other project that comes to mind with a separate docs repo, and they don't have a navbar: https://docs.conda.io/projects/conda/en/stable/user-guide/index.html

**Comment by kcpevey** [comment]
Napari keeps their docs separately and the link points to the code repo https://napari.org/dev/index.html 

But it fine if yall want to keep it pointing to the docs repo

**Comment by trallard** [comment]
I mostly want to avoid confusion with the origin of docs since as @pavithraes  mentioned we are not generating our docs from the `nebari` repo, yet there is a `docs/` directory there.

I would be happy to add a dropdown to navigate to multiple repos, WDYT?

**Comment by kcpevey** [comment]
I think a dropdown would be the most beneficial solution.
