### ISSUE TITLE
ENH - Upgrade conda-store to `0.4.9`

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docs#116]

**Comment by viniciusdc** [comment]
This bump will be included as part of the changes proposed in https://github.com/Quansight/qhub/pull/1357

**Comment by viniciusdc** [comment]
@costrouc what are the requirements needed for this update? when compared with the [current version v0.4.7](https://github.com/Quansight/qhub/pull/1385)

**Comment by viniciusdc** [comment]
This was completed by https://github.com/Quansight/qhub/pull/1392
