### ISSUE TITLE
[DOC] How to add JLab extensions

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#122]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

How to add common jlab extensions. Examples: Dask, Git

### Steps to Resolve this Issue

.

**Comment by pavithraes** [comment]
With JLab 4, I believe we can directly add several extensions by adding them to respective conda envs. This needs to be verified and documented. If this is not possible, the extensions will need to be included in the base docker images -- users can make requests by openeing issues on https://github.com/nebari-dev/nebari-docker-images. This workflow also needs to be documented

**Comment by kcpevey** [comment]
From @krassowski 

>This is not possible in the main JupyterLab server. There are workarounds, including making an app which starts JupyterLab. We can also solve this my swapping the extension manager class which I suggested before in planning and adjusting the path from which extensions get loaded dynamically.
>
>There is also an extension which allows to load some plugins without installation. We could adopt it for this use case.

This change would need to happen in nebari. So each user's jupyterlab instance would be looking to some local (to the user) place for extensions.

This is a feature request, not a documentation issue. I'll open one over on the nebari codebase.

**Comment by kcpevey** [comment]
There was already one over there :) https://github.com/nebari-dev/nebari/issues/2299
