### ISSUE TITLE
[DOC] How to use Grafana

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#124]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

How to setup/use Grafana

### Steps to Resolve this Issue

.

**Comment by pavithraes** [comment]
As discussed on Slack, we can close because we have https://www.nebari.dev/docs/how-tos/monitoring/#grafana
