### ISSUE TITLE
[DOC] Image formatting

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#130]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

I'd like to have the ability to add a border around my images to help differentiate it from the surrounding text. For example, when an image is a screen shot with white space in the middle, its hard to tell where the image ends. 

### Steps to Resolve this Issue

1. Sort out where this option should live (css?)
2. Sort out how to implement it for individual images?

**Comment by trallard** [comment]
This is now sorted, see https://www.nebari.dev/tutorials/using-vscode
