### ISSUE TITLE
[DOC] - Develop end user checklist for integrations

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#131]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Walk through actually using each of the integrations

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by kcpevey** [comment]
We essentially need a simple walkthrough for each integration. 

* [ ] vs code https://github.com/Quansight/qhub/issues/1384

**Comment by pavithraes** [comment]
Closing this META issue, we already have issue for some integrations and can open new ones for specific tools. :)
