### ISSUE TITLE
[DOC] - Fix broken link in Getting Started

### ISSUE THREAD

**Issue by magsol** [nebari-dev/nebari-docs#134]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

In the Getting Started guide, at the very end of the section for Installing Nebari, there's a note:

```
:::note Troubleshooting If you are unable to successfully validate the Nebari installation above, you may want to check out our [troubleshooting guide](https://github.com/nebari-dev/nebari-docs/blob/main/troubleshooting.md). :::
```

Given the [recent changeover](https://github.com/nebari-dev/nebari-docs/pull/97/commits/b8266d7bbc0191d1eb71e46a2234bbbed164ef04) to `mdx` suffix to allow for tabbed content, this link is now broken.

### Steps to Resolve this Issue

`troubleshooting.md` -> `troubleshooting.mdx`

**Comment by trallard** [comment]
This has been fixed, closing
