### ISSUE TITLE
[DOC] - Update keycloak docs to include details on differences between the different roles

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari-docs#137]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Keycloak has many wonderful features, many of which we are currently taking advantage of. However we need to make sure we document these. To start with, we should ensure that we have up-to-date docs that reflect the differences between all of the different roles that are available (i.e. `jupyterhub_admin` vs `jupyterhub_developer`). 

### Steps to Resolve this Issue

Ensure docs reflect current state of keycloak authentication/authorization.

**Comment by iameskild** [comment]
We can possible include this in the PR that is already open: #38

**Comment by pavithraes** [comment]
Closing as complete: https://www.nebari.dev/docs/how-tos/configuring-keycloak#in-depth-look-at-roles-and-groups :)
