### ISSUE TITLE
[DOC] - Add summary cards to front page

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#140]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Now that we've got some content filled out, we need work on making navigation easier. I'd like to implement some summary cards on the front page which will show people all the available pages at a glance without having to open up the folded sidebar tabs. 

### Steps to Resolve this Issue

Visual inspiration:
* https://www.gatsbyjs.com/docs/
* https://help.canary.tools/hc/en-gb

Implementation code examples:
* https://github.com/facebook/docusaurus/blob/main/website/src/components/Playground/index.tsx
* https://github.com/dailydotdev/docs/blob/main/src/components/homepage/homeNavBoxes.js
* https://github.com/Divine-Software/ghostly/blob/master/website/src/pages/index.js

**Comment by pavithraes** [comment]
@kcpevey I think our current welcome page addresses this issue: https://www.nebari.dev/docs/welcome

If you agree, we can close this as resolved. :)

**Comment by pavithraes** [comment]
Closing per the previous comment, please feel free to re-open if needed :)
