### ISSUE TITLE
[DOC] - Nebari API docs

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#157]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

* Need a reference of the multiple commands and examples

**Comment by pavithraes** [comment]
Start with CLI-related docstrings.

**Comment by trallard** [comment]
@kcpevey where are we up with API/CLI docs? we do not have anything documented right now an it would be best to point folks to these docs for example see https://github.com/orgs/nebari-dev/discussions/1587

**Comment by kcpevey** [comment]
This needs to be reviewed/merged https://github.com/nebari-dev/nebari-docs/pull/190 . Just realizing I have a mistake in the gh action, but it should still run locally.
