### ISSUE TITLE
[DOC] - Add maintainers guide to docs

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#159]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Need to add a developer guide

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by trallard** [comment]
This is a duplicate of #152 so closing for now
