### ISSUE TITLE
[DOC] Tutorial on upgrading Nebari

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#16]
* Good examples: https://docs.flyte.org/projects/cookbook/en/latest/integrations.html

[notion doc](https://www.notion.so/quansightlabs/Upgrade-Nebari-4c4d972c4c7c4cd7afb51706fdf45e30)

**Comment by trallard** [comment]
FastAPI tutorials are also great examples https://fastapi.tiangolo.com/tutorial/

**Comment by kcpevey** [comment]
Closing this since a how-to guide will be sufficient #17
