### ISSUE TITLE
[DOC] - add release notes

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#160]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Add release notes. Ideally this would be automated as much as possible.

Existing docs that need to be transferred/updated: https://docs.qhub.dev/en/latest/source/dev_guide/changelog.html

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by pavithraes** [comment]
Notes:
- [Release notes](https://github.com/Quansight/qhub/blob/main/RELEASE.md) are currently auto-generated by GitHub
- We can have a GitHub action to add it to the documentation

**Comment by pavithraes** [comment]
We may be able to use https://github.com/marketplace/actions/push-directory-to-another-repository

**Comment by pavithraes** [comment]
We can remove this issue from the milestone once #193 is merged. :)

Note that it will be fully resolved by https://github.com/Quansight/qhub/pull/1502
