### ISSUE TITLE
[DOC] - Migration guide for existing users

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-docs#168]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

- How does the QHub -> Nebari renaming affect existing users
- What are the steps they need to take to update their instances

### Steps to Resolve this Issue

n/a

**Comment by pavithraes** [comment]
Note -- we need to add a link to this migration guide in `faq#how-do-i-migrate-qhub-to-nebari` which was added in #115

**Comment by pavithraes** [comment]
xref: https://github.com/orgs/nebari-dev/discussions/1604

**Comment by kcpevey** [comment]
I think [this PR](https://github.com/nebari-dev/nebari-docs/pull/267) covers this topic for migrating from pre 0.4 to 0.4+
