### ISSUE TITLE
[DOC] - Clean up the img folder

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#179]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

We moved towards keeping the images in folders associated with the documentation type, but there a few stragglers that need to be cleaned up. 

Need to be moved:
* [k9s_UI.png](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/k9s_UI.png)
* [x_array.png](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/x_array.png)
* [z_array.png](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/z_array.png)

Possibly unused:
* [docusaurus.png](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/docusaurus.png)
* [favicon.ico](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/favicon.ico)
* [logo.svg](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/logo.svg)
* [undraw_docusaurus_mountain.svg](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/undraw_docusaurus_mountain.svg)
* [undraw_docusaurus_react.svg](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/undraw_docusaurus_react.svg)
* [undraw_docusaurus_tree.svg](https://github.com/nebari-dev/nebari-docs/blob/main/docs/static/img/undraw_docusaurus_tree.svg)

### Steps to Resolve this Issue

.

**Comment by riquelmebandeira** [comment]
Hey @kcpevey, i'll work on it :)
