### ISSUE TITLE
[DOC] Tutorial - Nebari 101 Quickstart

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#18]
See [notion doc](https://www.notion.so/quansightlabs/Nebari-101-quickstart-07657e8af98645a29026f9bca7927e2f)

**Comment by pavithraes** [comment]
Just a note, take inspiration from https://spacy.io/usage/spacy-101 for this page.

**Comment by pavithraes** [comment]
Another note from the standup, we can include the "Monitoring" capabilities of Nebari in this page.

**Comment by pavithraes** [comment]
Next step: Re-evaluate the purpose, audience, and content of this doc.

**Comment by kcpevey** [comment]
Seems like we decided to close with the closure of #216 ?
