### ISSUE TITLE
[ENH] - Nebari website OSS

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docs#182]
🎨 The site can be found at: https://www.figma.com/file/48vtmwvvuw8OjRV6Gp9bk9/Nebari-website?node-id=0%3A1

## Updates
- [x] The design was internally discussed and pre-approved
- [x] There are several comments by @laisbsc aimed at aligning the sections and some content

## Needs discussion
- [x] Need to align with Irina to develop some illustrations for some of the sections
- [x] Content copy tracked in #167

**Comment by pavithraes** [comment]
TODOs for the GIF:
- https://github.com/nebari-dev/nebari-docs/pull/167
- https://github.com/Quansight/qhub/issues/1390
- https://github.com/Quansight/qhub/issues/1446
