### ISSUE TITLE
[DOC] - Update end user conda-store tutorial with new UI

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-docs#197]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Docs page to update: https://www.nebari.dev/tutorials/creating-new-environments

New UI: https://github.com/Quansight/conda-store-ui

Review and update the content+images!

**Comment by pavithraes** [comment]
Just to cross-link, this is the PR that adds the new conda-store UI to Nebari: https://github.com/nebari-dev/nebari/pull/1564

**Comment by kcpevey** [comment]
Need to add conda-store instructions to [this FAQ question](https://www.nebari.dev/docs/faq#what-if-i-need-to-install-package-x-and-its-not-available-in-the-environment). And a link to conda-store tutorial which I imagine is a separate part of this issue.
