### ISSUE TITLE
[DOC] - Update banner to have a warning for existing users

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-docs#199]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

We can update the existing banner to have a warning for existing QHub users:
- the project has been renamed, which means older clusters will break
- cloud deployments will see a re-deploy

### Steps to Resolve this Issue

tbd

**Comment by trallard** [comment]
Added in a previous PR closing now
