### ISSUE TITLE
[BUG] - 404 Not found pages

### ISSUE THREAD

**Issue by eliasdabbas** [nebari-dev/nebari-docs#206]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

These pages are returning a 404 not found status code: 

https://www.nebari.dev/docs/docs/troubleshooting#handle-access-to-restricted-namespaces
https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry
https://www.nebari.dev/docs/how-tos/docs/troubleshooting
https://www.nebari.dev/how-tos/nebari-gcp#deploying-nebari
https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari
https://www.nebari.dev/docs/how-tos/docs/tutorials
https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-azure#nebari-initialize
https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-do#nebari-initialize
https://www.nebari.dev/docs/get-started/docs/how-tos/nebari-local
https://www.nebari.dev/docs/get-started/docs/get-started/cloud-providers
https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-aws#nebari-initialize
https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-gcp#nebari-initialize

It seems something is adding a redundant `/docs/` or `/docs/how-tos/` folders somehow.

These pages are linked to from these pages: 

|    | url                                                                      | not found links                                                                                   |
|---:|:-------------------------------------------------------------------------|:----------------------------------------------------------------------------------------|
|  0 | https://www.nebari.dev/docs/troubleshooting/                             | https://www.nebari.dev/docs/docs/troubleshooting#handle-access-to-restricted-namespaces |
|  1 | https://www.nebari.dev/docs/how-tos/domain-registry/                     | https://www.nebari.dev/how-tos/nebari-gcp#deploying-nebari                              |
|  2 | https://www.nebari.dev/docs/how-tos/domain-registry/                     | https://www.nebari.dev/how-tos/nebari-gcp#deploying-nebari                              |
|  3 | https://www.nebari.dev/docs/how-tos/nebari-azure/                        | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari                  |
|  4 | https://www.nebari.dev/docs/how-tos/nebari-azure/                        | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                                |
|  5 | https://www.nebari.dev/docs/how-tos/nebari-azure/                        | https://www.nebari.dev/docs/how-tos/docs/tutorials                                      |
|  6 | https://www.nebari.dev/docs/how-tos/nebari-azure/                        | https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-azure#nebari-initialize         |
|  7 | https://www.nebari.dev/docs/how-tos/nebari-azure/                        | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry                        |
|  8 | https://www.nebari.dev/docs/how-tos/nebari-do/                           | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari                  |
|  9 | https://www.nebari.dev/docs/how-tos/nebari-do/                           | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                                |
| 10 | https://www.nebari.dev/docs/how-tos/nebari-do/                           | https://www.nebari.dev/docs/how-tos/docs/tutorials                                      |
| 11 | https://www.nebari.dev/docs/how-tos/nebari-do/                           | https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-do#nebari-initialize            |
| 12 | https://www.nebari.dev/docs/how-tos/nebari-do/                           | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry                        |
| 13 | https://www.nebari.dev/docs/get-started/deploy/                          | https://www.nebari.dev/docs/get-started/docs/get-started/cloud-providers                |
| 14 | https://www.nebari.dev/docs/get-started/deploy/                          | https://www.nebari.dev/docs/get-started/docs/how-tos/nebari-local                       |
| 15 | https://www.nebari.dev/docs/how-tos/nebari-aws/                          | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari                  |
| 16 | https://www.nebari.dev/docs/how-tos/nebari-aws/                          | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                                |
| 17 | https://www.nebari.dev/docs/how-tos/nebari-aws/                          | https://www.nebari.dev/docs/how-tos/docs/tutorials                                      |
| 18 | https://www.nebari.dev/docs/how-tos/nebari-aws/                          | https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-aws#nebari-initialize           |
| 19 | https://www.nebari.dev/docs/how-tos/nebari-aws/                          | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry                        |
| 20 | https://www.nebari.dev/docs/how-tos/nebari-gcp/                          | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari                  |
| 21 | https://www.nebari.dev/docs/how-tos/nebari-gcp/                          | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                                |
| 22 | https://www.nebari.dev/docs/how-tos/nebari-gcp/                          | https://www.nebari.dev/docs/how-tos/docs/tutorials                                      |
| 23 | https://www.nebari.dev/docs/how-tos/nebari-gcp/                          | https://www.nebari.dev/docs/how-tos/docs/how-tos/nebari-gcp#nebari-initialize           |
| 24 | https://www.nebari.dev/docs/how-tos/nebari-gcp/                          | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry                        |
| 25 | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry         | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry                        |
| 26 | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry         | https://www.nebari.dev/docs/how-tos/docs/how-tos/domain-registry                        |
| 27 | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                 | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                                |
| 28 | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                 | https://www.nebari.dev/docs/how-tos/docs/troubleshooting                                |
| 29 | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari   | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari                  |
| 30 | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari   | https://www.nebari.dev/docs/how-tos/docs/get-started/installing-nebari                  |
| 31 | https://www.nebari.dev/docs/how-tos/docs/tutorials                       | https://www.nebari.dev/docs/how-tos/docs/tutorials                                      |
| 32 | https://www.nebari.dev/docs/how-tos/docs/tutorials                       | https://www.nebari.dev/docs/how-tos/docs/tutorials                                      |
| 33 | https://www.nebari.dev/docs/get-started/docs/how-tos/nebari-local        | https://www.nebari.dev/docs/get-started/docs/how-tos/nebari-local                       |
| 34 | https://www.nebari.dev/docs/get-started/docs/how-tos/nebari-local        | https://www.nebari.dev/docs/get-started/docs/how-tos/nebari-local                       |
| 35 | https://www.nebari.dev/docs/get-started/docs/get-started/cloud-providers | https://www.nebari.dev/docs/get-started/docs/get-started/cloud-providers                |
| 36 | https://www.nebari.dev/docs/get-started/docs/get-started/cloud-providers | https://www.nebari.dev/docs/get-started/docs/get-started/cloud-providers                |

### Steps to Resolve this Issue

1. Check how the wrong URL path parts are being added (script, manually, etc.)
2. Remove it

**Comment by iameskild** [comment]
Hi @eliasdabbas, thanks for reporting this! We are still in the process of migrating our docs from qhub.dev to nebari.dev but it's great to know exactly where we need to focus our attention, much appreciated :)

**Comment by trallard** [comment]
Thanks for reporting this issue. Seems the recent changes made to add the landing page messed up internal cross-references. 

Our current config should have caught broken links and thrown an error but it seems it needs debugging.
Will fix this straight away!
