### ISSUE TITLE
[DOC] Conceptual Guides - overview page is empty

### ISSUE THREAD

**Issue by kshitij12345** [nebari-dev/nebari-docs#209]
Ref: https://www.nebari.dev/docs/explanations/overview

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/19503980/199832868-20abf599-e669-4c4f-8625-ebe9b09b0a94.png">

**Comment by pavithraes** [comment]
@kshitij12345 Thanks for opening this issue! We already have #183 to track this and similar overview docs improvements, so I'll close this in favor of the broader issue. :)
