### ISSUE TITLE
[DOC] - Add section about version mismatch on troubleshooting

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari-docs#210]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Sometimes the user might encounter the following error message if the installed version of nebari and the one specified in the `nebari-config.yaml` does not match:
```
Error: The schema validation of the nebari-config.yaml failed.
The following error message may help determine what went wrong:
nebari_version
  nebari_version in the config file must be equivalent to <installed version> to be
  processed by this version of nebari (your config file version is <nebari_version>).
  Install a different version of qhub or run nebari upgrade to ensure your config
  file is compatible.
(type=value_error)
```
which will cause nebari not to deploy.

### Steps to Resolve this Issue

1. Add a new troubleshooting section explaining the above situation and a resolution

**Comment by pavithraes** [comment]
It's now documented here: https://www.nebari.dev/docs/explanations/config-best-practices#nebari-version-assertion
Closing as completed :)
