### ISSUE TITLE
[DOC] - Create landing page video/gif

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-docs#212]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

xref: #182

This issue is to track and iterate on the video/gif for the "Get started" section of the landing page.

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by pavithraes** [comment]
@trallard Here is the video demo we made for PyData NYC: [link to upload on google drive](https://drive.google.com/file/d/16KDoDnxU7zSA5MpyMc6jth_wTFR6ewev/view?usp=sharing) (1:26 minutes long)

Shall we use this same video for the website, with the end slide updated to say something like "Get started: `nebari.dev/docs`"? Or, we can also remove the intro and end slides all together.

Would you like to make any other updates to the video?

**Comment by trallard** [comment]
how would we add this to our landing page? - we need to make sure we have a reliable source and that the way we embed this is not too problematic

maybe we could create a smaller/shorter gif?

**Comment by pavithraes** [comment]
@trallard [Here is a shorter GIF with only Nebari deployment!](https://drive.google.com/file/d/1VF04x_yOv4jkcEv-fz7z_H1dc5xCK_Y4/view?usp=sharing)

What do you think? Would you like to make any changes?

**Comment by trallard** [comment]
This will definitely work! Thanks for sorting this so quickly. Please go ahead and share with Gabriel
