### ISSUE TITLE
[DOC] - Document TF Extensions and Helm extensions

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari-docs#246]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Currently this feature is depended on by several clients that I am aware of. This feature needs to be documented.

### Steps to Resolve this Issue

See https://github.com/nebari-dev/nebari/discussions/1601

**Comment by pavithraes** [comment]
Closing this issue, we can track the task in https://github.com/nebari-dev/nebari-docs/issues/163 :)
