### ISSUE TITLE
[DOC] Update kbatch doc

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#253]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

The kbatch tutorial docs don't run. There are other examples that DO run in the `/shared/examples` folder which ships with nebari. We need to update the kbatch tutorial with these working examples. 

### Steps to Resolve this Issue

.

**Comment by iameskild** [comment]
@kcpevey I'm closing this issue. It looks like your PR #260 took care of it :)
