### ISSUE TITLE
[DOC] Update dashboard examples

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#254]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Related to [removing the examples](https://github.com/nebari-dev/nebari/issues/1558) we have in the `/shared/examples` folder. 

We need to find better examples. Ideas:

streamlit: https://github.com/jkanner/streamlit-dataview
dash: https://github.com/plotly/dash-sample-apps/tree/main/apps/dash-oil-and-gas

Still need an idea for voila.

Add the example repos as submodule(s) or notebooks in nebari-demo.

Add a mention and link in the dashboard docs.

Other dashboards docs: https://github.com/nebari-dev/nebari-docs/issues/239 and https://github.com/nebari-dev/nebari-docs/issues/242

### Steps to Resolve this Issue

.

**Comment by pavithraes** [comment]
I think we can call this done, we now have https://github.com/nebari-dev/nebari-demo/tree/main/dashboard_examples & we also have example in the JHub Apps docs
