### ISSUE TITLE
[DOC] -  Nebari multi-cloud architectural diagrams

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docs#27]
We are lacking in-depth / up-to-date architectural diagrams

- [ ] #28
- [ ] #29
- [ ] #30
- [ ] #31

Diagrams should be added to https://lucid.app/documents#/documents?folder_id=278399173

**Comment by kcpevey** [comment]
See previous meta issue: https://github.com/Quansight/qhub/issues/1031
