### ISSUE TITLE
[BUG] - https://www.nebari.dev/docs/how-tos/nebari-azure bugs

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari-docs#275]
### Describe the bug

https://www.nebari.dev/docs/how-tos/nebari-azure has a line "Refer to [Conceptual guides] for more information on how Nebari's components are secured."  Conceptual guides is supposed to be a link but it's not right now.

~Additionally, the screenshot under guided-init shows `project-name` even though it'll throw an error if users use dashes.~
![image](https://user-images.githubusercontent.com/23342526/221994688-03471b15-fb76-4a45-8915-e4ec646a0152.png)

### Expected behavior

link

### OS and architecture in which you are running Nebari

h

### How to Reproduce the problem?

h

### Compute environment

None

**Comment by pavithraes** [comment]
Thanks for sharing! I've made a note of the second-half (about project name) in https://github.com/nebari-dev/nebari/issues/1478, so I'll strike it from this issue.
