### ISSUE TITLE
Suggestion:  Add to docs - How to specify a custom VNet in Nebari? 

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari-docs#277]
### Context

Docs website doesn't have any info on how to to specify a custom VNet in Nebari though the repo docs do (https://github.com/nebari-dev/nebari/blob/develop/docs/source/installation/configuration.md#deployment-inside-virtual-private-network).  Maybe add to FAQ? 

### Value and/or benefit

Increased clarity

**Comment by pavithraes** [comment]
This will be covered by #115
