### ISSUE TITLE
Improve Argo integration

### ISSUE THREAD

**Issue by dharhas** [nebari-dev/nebari-docs#278]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

~We need to add basic usage documentation for Argo Workflows.~

~I recently answered this question on another repo that is trying Nebari + Argo with an example form a recent demo:~

~https://github.com/asascience-open/nextgen-dmac/issues/30#issuecomment-1450267325~

~This needs to be cleaned up and added in the appropriate location in the docs.~

**Two additional non-docs questions:**
- should we consider shipping the argo cli in the base image
- is there a way to auto set these user specific secrets for each user

### Steps to Resolve this Issue

~1. Add Argo usage docs to nebari's docs.~

**Comment by pavithraes** [comment]
Thanks for opening this issue! I've moved over the documentation notes to #48, where we're tracking Argo-docs. I'll edit this issue to discuss the other two questions.

**Comment by Adam-D-Lewis** [comment]
> is there a way to auto set these user specific secrets for each user
The way thay comes to mind is to allow KubeSpawner to impersonate Nebari users (like we do from Keycloak UI), gain an Argo access token, then set it as an env var for the user pod

**Comment by kcpevey** [comment]
>The way thay comes to mind is to allow KubeSpawner to impersonate Nebari users (like we do from Keycloak UI), gain an Argo access token for the user, then set it as an env var for the user pod

I believe this has been done. @iameskild can you confirm?

**Comment by kcpevey** [comment]
Consideration of adding the Argo CLI to the base image is now an open issue in the main repo: https://github.com/nebari-dev/nebari/issues/1850
