### ISSUE TITLE
[DOC] - Add docs on how to deploy nebari with custom certificate

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari-docs#279]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Users may want to deploy Nebari with a custom SSL cert and we should have some docs on how to do so.

### Steps to Resolve this Issue

N/A

**Comment by Adam-D-Lewis** [comment]
The way to do it currently is to deploy with self signed cert, then add a TLS cert as a kubernetes secret manually, then update the nebari-config file and redeploy.

**Comment by pavithraes** [comment]
This will be covered by #115 :)
