### ISSUE TITLE
[DOC] - FAQ for troubleshooting Dask

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#292]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

We have an FAQ item from the old docs that hasn't been migrated. 

![image](https://user-images.githubusercontent.com/15659110/227249999-5fc2a533-f4b7-48c7-aff8-bbe1dfe5b07b.png)

### Steps to Resolve this Issue

add doc to FAQ

**Comment by pavithraes** [comment]
Thanks! Minor note, I think this will be more suited for the Troubleshooting page: https://www.nebari.dev/docs/troubleshooting :)

**Comment by pavithraes** [comment]
Dask now provides better error messages. Closing as not planned.
