### ISSUE TITLE
[DOC] - Dev environment setup instructions are outdated

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari-docs#302]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

On https://www.nebari.dev/docs/community/code-contributions#create-a-virtual-environment, it says "Create a new environment using environment-dev.yaml", but the nebari repo doesn't have an environment-dev.yaml anymore. 

### Steps to Resolve this Issue

We should update to `pip install -e .[dev]`

**Comment by pavithraes** [comment]
Resolved by #305
