### ISSUE TITLE
[DOC] - environment-dev.yaml does not exist

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari-docs#307]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

The [virtual environment section within the code contribution guidelines](https://www.nebari.dev/docs/community/code-contributions/#create-a-virtual-environment)

speaks of an `environment-dev.yaml`, but this file [does not exist](https://github.com/nebari-dev/nebari/tree/cdd2d34ca0fed18978e30c66f91bf28b7e66ea15). 

In addition, step 2. says to use the file mentioned above, but then the command displayed does not work if we had this file in the first place. My guess is that we had this file at some point, but forget to update the text here, but have updated the code.

### Steps to Resolve this Issue

One of

- create / reinstate `environment-dev.yaml` and fix the code in step 2.
- fix the text in the whole section to not mention `environment-dev.yaml`

**Comment by pavithraes** [comment]
Partially resolved by #305, but we missed the text. I'll open another PR.
