### ISSUE TITLE
[DOC] - Incorrect branch in Develop your contribution section of Contribute to Nebari's codebase

### ISSUE THREAD

**Issue by babueverest** [nebari-dev/nebari-docs#311]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

**What is the Issue ?**
The **Develop your contribution** section of [Contribute to Nebari's codebase](https://www.nebari.dev/docs/community/code-contributions#develop-your-contribution) asks the developer to checkout their feature branch out of main branch.

**What it should have been?** 
The developer is supposed to checkout feature branch out of develop branch.

**Fix**
Change the documentation to have develop branch instead of main branch.

### Steps to Resolve this Issue

Change the documentation to have develop branch instead of main branch.

**Comment by pavithraes** [comment]
Welcome, and thank you for reporting!

**Comment by pavithraes** [comment]
Has now been updated :)
