### ISSUE TITLE
[DOC] - How to use Jitsi in Nebari

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-docs#324]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

- Create and share new rooms out the box
- How to set up have some default rooms
- How to access it, and link to Jitsi docs more moderation, etc.
- Make a note about changing tab sizes refreshes the room, needed a re-login

### Steps to Resolve this Issue

TBD

**Comment by kcpevey** [comment]
Closing since we no longer support jitsi.
