### ISSUE TITLE
[DOC] How to manage environments with conda-store (i.e., configure conda-store)

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#34]
See also https://github.com/Quansight/qhub/issues/1276 : 
```
There are some recent issues related to Conda-store usage on qhub (see  
 https://github.com/Quansight/qhub/issues/1262 for example) that identify some issues with our [current doc of this service](https://docs.qhub.dev/en/latest/source/user_guide/environments.html?highlight=conda-store).  
 Also, there seems to be some outdated information presented in there as well.  

* Update main docs, to explain how to use conda-store, and differences between default/filesystems environments from the conda-store managed ones.
* Update paragraph related to authentication mechanic (we now support OAuth redirection)
```

Existing doc: https://docs.qhub.dev/en/latest/source/user_guide/environments.html?highlight=conda-store

[Notion page](https://www.notion.so/quansightlabs/Manage-environments-with-Conda-Store-bab4e41e5c1a4e66bfbc236506bbc178)

**Comment by kcpevey** [comment]
Need to review existing one https://www.nebari.dev/tutorials/creating-new-environments and make updates as needed

**Comment by pavithraes** [comment]
From https://github.com/nebari-dev/nebari-docs/pull/178#discussion_r994043838, making a note here so we can keep track of this conversation :)

> iameskild - Do we have instructions on how to delete these outdated namespaces?
> viniciusdc - Unfortunately not, I added the endpoint link to the namespaces UI page as an attempt to showcase the delete button in there, but I agree that an in-depth section somewhere would be good -- I think this ties in with the conda-store management docs that will be written

**Comment by pavithraes** [comment]
We have a new issue #197 to track the end-user docs -- end-user docs are a higher priority right now, so we're adding it to the milestone.

Consecutively, this issue can track the admin docs, which we can prioritize later and hence, removing the milestone. :)

**Comment by pavithraes** [comment]
Noting a few more things to include in this doc:
- How to configure allowed channels in `nebari-config.yaml` (we can at least add a note this this doc even if the details are a part of advanced config docs), ref: `https://github.com/nebari-dev/nebari/issues/1594`
- Mention that there is currently no way to "disable" conda-store, ref: `https://github.com/orgs/nebari-dev/discussions/1150#discussioncomment-4323965`

**Comment by kcpevey** [comment]
I think this will be closed by https://github.com/nebari-dev/nebari-docs/pull/399

**Comment by kcpevey** [comment]
Closing since #399 is merged!
