### ISSUE TITLE
[BUG] - VS Code prevents idle culler from shutting down server

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#351]
### Describe the bug

If you have VS Code open on Nebari, your server will never shutdown (even if your browser page is minimized and you don't touch the server for hours). 

### Expected behavior

I expect the idle culler to shutdown my server even when I accidentally leave a stray window open. 

### OS and architecture in which you are running Nebari

AWS

### How to Reproduce the problem?

First to prove the idle culler works:

- Start a Nebari server of any size. 
- Minimize the browser window (or open another tab)
- Leave it alone for more than the idle culler timeout (45 min is super safe if you dont know what it is). 
- Open up the browser window again and you'll see that the server has been shutdown. 

Next prove that VS Code keeps it alive:

- Start a Nebari server of any size.
- Start VS Code 
- Minimize the browser windows (or open another tab)
- Leave it alone for more than the idle culler timeout (45 min is super safe if you dont know what it is). 
- Open up the browser window again and you'll see that the server has **NOT** been shutdown 

### Compute environment

None

**Comment by kcpevey** [comment]
The FAQ item needs to be include a mention that the VS Code service counts as a `non-jupyterlab server` - that's not something I would have known as an end user. 

That said, I'm not sure adding an FAQ item is sufficient. Who is going to read about this in an FAQ? Someone would have to stumble upon it. Is there any way for us to add a jupyterlab banner or warning dialog reminding people of this behavior when they click on the vs code icon?

**Comment by pavithraes** [comment]
> Is there any way for us to add a jupyterlab banner or warning dialog reminding people of this behavior when they click on the vs code icon?

@iameskild Do you know if this is possible? I recall discussions about a launcher enhancement, would this note about VSCode be in scope for that? If yes, we can move this issue back to the nebari repo. :)

**Comment by kcpevey** [comment]
> If yes, we can move this issue back to the nebari repo. :)

FAQ item and maybe even a mention on the VS Code docs page are still necessary. I'd suggest a separate issue in the nebari repo if a banner is possible

**Comment by ericdatakelly** [comment]
As a vscode user, I don't think I would review the docs related to vscode unless I came across a problem.  It would be nice to have a message on screen instead.

I don't know much about vscode extensions, but I think a simple one could be run at startup that just displays a welcome page.  The welcome message could be markdown and easily edited by developers. 

Should I pursue this or stick with just documentation changes?  I can also ask some UI folks if they think this is easy or not.

**Comment by kcpevey** [comment]
I'd like to mention this as a "warning" on the VSCode docs page and as an FAQ item. 

We'd have to investigate if a banner is possible or where it should go. I can ask the team for ideas and options.

**Comment by kcpevey** [comment]
Closed by #457
