### ISSUE TITLE
[DOC] - Add how-to connect using jupyterhub-ssh

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari-docs#377]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

This is currently a feature we have but isn't included in the docs. It might be cool to show a user connected via their VScode using Co-Pilot or another AI tool.

### Steps to Resolve this Issue

Add instructions.

**Comment by Adam-D-Lewis** [comment]
There are some instructions in https://github.com/nebari-dev/nebari-demo/blob/main/01_interface.ipynb but we should add to this repo as well.

**Comment by Adam-D-Lewis** [comment]
Ideally, as part of these docs, we will list what the minimum scopes that are needed for the token.
