### ISSUE TITLE
[DOC] - Monitoring with Grafana + Prometheus

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari-docs#381]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Add documentation for the existing monitoring tools and dashboards that are deployed with Nebari.

### Steps to Resolve this Issue

None

**Comment by kcpevey** [comment]
Grafana monitoring now has its own page. Improvements to this page are covered in #393 and #442 in more detail.
