### ISSUE TITLE
[DOC] - CDS Dashboards and Kbatch still referenced in docs

### ISSUE THREAD

**Issue by dcmcand** [nebari-dev/nebari-docs#389]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Kbatch and CDS Dashboards have both been depreciated, but are still referenced in the documentation.

### Steps to Resolve this Issue

1. Remove references to Kbatch
2. Remove referenced to CDS Dashboards

**Comment by pavithraes** [comment]
kbatch references were removed in `#390` (thanks, Chuck!), re-opening to keep track of removing cdsdashboards docs when we have a replacement merged.

**Comment by kcpevey** [comment]
The docs have been updated to indicate that [CDS Dashboards doc](https://www.nebari.dev/docs/tutorials/create-dashboard#deploy-and-share-the-dashboard-with-cds-dashboards-nebari-v202371-or-earlier) is relevant to earlier versions and we have new docs for [jhub app launching](https://www.nebari.dev/docs/tutorials/create-dashboard#deploy-the-dashboard-with-jhub-app-launcher). This is complete.
