### ISSUE TITLE
[DOC] - Dask documentation items

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docs#39]
## Summary
Should up-to date docs on Dask - effectively replacing / updating https://docs.qhub.dev/en/latest/source/user_guide/dask_gateway.html

## Tasks to complete

- [x] [DOC] - Tutorial: Using Dask (https://github.com/nebari-dev/nebari/issues/12)
- [ ] [DOC] - How-to: configure Dask (https://github.com/nebari-dev/nebari/issues/68)

## Examples

Flyte integrations page https://docs.flyte.org/projects/cookbook/en/latest/integrations.html

**Comment by trallard** [comment]
- Dask gateway
 - Dask distributed

**Comment by iameskild** [comment]
Additional dask-related docs:
https://docs.qhub.dev/en/latest/source/installation/configuration.html?highlight=dask

**Comment by kcpevey** [comment]
current discussion of Dask in the docs:

* https://docs.qhub.dev/en/stable/source/admin_guide/system_maintenance.html?highlight=dask#setting-specific-dask-workers-to-run-on-a-nodegroup
* https://docs.qhub.dev/en/stable/source/user_guide/dask_gateway.html?highlight=dask#using-dask-gateway
* https://docs.qhub.dev/en/stable/source/installation/configuration.html?highlight=dask#dask-scheduler
* https://docs.qhub.dev/en/stable/source/installation/configuration.html?highlight=dask#dask-profiles
* https://docs.qhub.dev/en/stable/source/user_guide/dask_gateway.html?highlight=dask#setting-conda-environment-for-dask-workers
* https://docs.qhub.dev/en/stable/source/user_guide/dask_gateway.html?highlight=dask#common-errors
* https://docs.qhub.dev/en/stable/source/admin_guide/faq.html?highlight=dask#on-aws-why-do-user-instances-occasionally-die-30-minutes-after-spinning-up-a-large-dask-cluster
* https://docs.qhub.dev/en/stable/source/user_guide/faq.html?highlight=dask#what-s-included-in-the-user-environment-if-a-user-wants-to-use-dask
* https://docs.qhub.dev/en/stable/source/user_guide/faq.html?highlight=dask#how-can-a-user-install-a-local-package-is-it-available-to-the-user-s-dask-workers

I will split this out into Tutorial and How-to soon.

**Comment by trallard** [comment]
What is the status of this @kcpevey this issue seems to have been marked as in progress for an awful lot
