### ISSUE TITLE
Update docs for scaling to zero nodes in AWS

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-docs#410]
### Context

Update docs related to: https://github.com/nebari-dev/nebari/pull/2168

In https://www.nebari.dev/docs/explanations/provider-configuration, AWS:

>[Amazon Web Services](https://aws.amazon.com/) has similar support to DigitalOcean and doesn't allow auto-scaling below 1 node.

Update the above to 0

### Value and/or benefit

Up to date docs

**Comment by kcpevey** [comment]
This was completed in https://github.com/nebari-dev/nebari-docs/pull/456
