### ISSUE TITLE
[DOC] - git repo auto-deploy explanation and examples

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#437]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

We've added a mechanism to provide all users with a copy of any git repo but it has not yet been documented (or if it is, make it more findable)

This is defined in nebari-config.yml and checked when the user server is started. 

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by kcpevey** [comment]
Should probably go in https://www.nebari.dev/docs/explanations/advanced-configuration/

**Comment by pavithraes** [comment]
We have some docs here: https://www.nebari.dev/docs/explanations/custom-overrides-configuration#jupyterlab

We need to add a little more descriptive text to ensure this shows up on common search terms

**Comment by kcpevey** [comment]
All the references in the docs call it "initial_repositories" which I did not think to use as a search term when I was trying to find this feature in the docs. I was trying terms like `git repo` and `auto-deploy` which also don't seem like great names, but its all I could think of.
