### ISSUE TITLE
[DOC] - Expand Loki end user documentation

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#442]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

We have basic usage docs for loki, but we are lacking usecase documentation. Some things that initially come to mind:

How do I... 
* Check logs for my deployed apps?
* Check logs for my jupyter server?
* Check logs for conda-store (server/worker)?
* See how many people are on the platform?
* Check memory usage of my server?

### Steps to Resolve this Issue

These docs need to be expanded: https://www.nebari.dev/docs/how-tos/monitoring#loki

**Comment by kcpevey** [comment]
Related admin level doc issue: https://github.com/nebari-dev/nebari-docs/issues/393

**Comment by kcpevey** [comment]
Blocked by grafana upgrade.

**Comment by kenafoster** [comment]
Some of the items in the description require fixes to dashboards (which are developed in Angular, now deprecated)

- See how many people are on the platform?
- Check memory usage of my server?

Meta issue created on Nebari side to track fixes: https://github.com/nebari-dev/nebari/issues/2591
