### ISSUE TITLE
[DOC] Tutorial on Long running workflows via kbatch

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#46]
Good starting point may be shared/examples/kbatch_nb.ipynb on qhub-beta

**Comment by trallard** [comment]
@iameskild  to review  - might need splitting and tidying 🧹

**Comment by trallard** [comment]
@kcpevey  to make a decision to mark as complete or split

**Comment by kcpevey** [comment]
I am going to close as this is complete. Additional improvements may need to be made, but those should requested/summarized as a separate issue. @iameskild
