### ISSUE TITLE
[DOC] Tutorial on using Argo Workflows

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#48]
[Current documentation](https://docs.qhub.dev/en/latest/source/admin_guide/argo-workflows.html)

Need to review the current documentation for accuracy and transform into a tutorial aimed at end users.

**Comment by kcpevey** [comment]
https://docs.qhub.dev/en/latest/source/admin_guide/argo-workflows.html

See also https://github.com/nebari-dev/nebari-docs/issues/49

**Comment by pavithraes** [comment]
Noting Dharhas' comment from #278:

> We need to add basic usage documentation for Argo Workflows.
> 
> I recently answered this question on another repo that is trying Nebari + Argo with an example form a recent demo:
> 
> `https://github.com/asascience-open/nextgen-dmac/issues/30#issuecomment-1450267325`
> 
> This needs to be cleaned up and added in the appropriate location in the docs.
