### ISSUE TITLE
[DOC] - Add troubleshooting doc for "too many open files" in kind cluster 

### ISSUE THREAD

**Issue by asmacdo** [nebari-dev/nebari-docs#495]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Running the local deployment docs https://www.nebari.dev/docs/how-tos/nebari-local did not succeeed.

There were a couple of issues (DNS is still unresolved, but I'll post in a separate issue)

### Steps to Resolve this Issue

`kind` cluster needs a higher ulimit

Resolved by:
```
sudo sysctl fs.inotify.max_user_watches=524288      
sudo sysctl fs.inotify.max_user_instances=512
```

I can add a blurb to https://www.nebari.dev/docs/troubleshooting or https://www.nebari.dev/docs/how-tos/nebari-local if that would be helpful :)

**Comment by viniciusdc** [comment]
> I can add a blurb to [nebari.dev/docs/troubleshooting](https://www.nebari.dev/docs/troubleshooting)
that would be great

```
sudo sysctl fs.inotify.max_user_watches=524288      
sudo sysctl fs.inotify.max_user_instances=512
```
Strangely enough, I also remember doing this once, but I never encountered it again so I forgot it (should've documented), here's a link that you can add to a note in our PR if you feel comfortable with it https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
