### ISSUE TITLE
[DOCS] - Integrate intake catalog data into tutorials

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari-docs#56]
Although there is some cleanup needed (on the intake catalog), it would be wonderful if we could integrate the intake catalog datasets into the tutorials. This way when the user tries Nebari for the first time, they can get started following our tutorials that show off a few services working together (read: data science workflows). 

The idea of showing off more than one service working together need not involve intake but if you're starting with data, perhaps it would make it easier if we standardized the approach.

cc @tonyfast @sayantikabanik

**Comment by sayantikabanik** [comment]
💯 to the idea of `standardized the approach`. 

Though I feel coupling multiple tools for example `intake` might be a little overwhelming to our users. Unless we could figure out ways to add an abstraction layer. Happy to discuss this further 🙂

**Comment by iameskild** [comment]
I agree, there is definitely a possibility that this could overcomplicate things. A deeper discussion with as a team is a good place to start :)

**Comment by kcpevey** [comment]
We had started creating a package for the intake catalog that we could use for demo dashboards. The thinking is that we could use that for more complex dashboards. It might be neat to use it for some of the more complex usecases or for larger datasets (but leave it off the simple tutorials like @sayantikabanik mentioned). However, the package work sort of got off course. We need to get that work complete before we can implement it in the docs here.

**Comment by pavithraes** [comment]
This was deprioritized, so closing as not planned. Please feel free to re-open when needed. :)
