### ISSUE TITLE
[DOC] Add Nebari logo to readme

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari-docs#62]
add nebari logo to readme once it is finalized.

**Comment by rsignell-usgs** [comment]
![2022-06-24_14-19-20](https://user-images.githubusercontent.com/1872600/175627888-566833bf-6d60-4d89-8d5e-58ce5b1573f0.jpg)

**Comment by rsignell-usgs** [comment]
Seems either of these could be used to create a nice stylized logo!   (or maybe the logo development is well underway?)

**Comment by kcpevey** [comment]
Thanks @rsignell-usgs! This is a good start. We are still working on the design and logo and we'll add these to the inspiration :)
