### ISSUE TITLE
[DOC] - Add a search bar for Nebari docs

### ISSUE THREAD

**Issue by HarshCasper** [nebari-dev/nebari-docs#73]
## Description

The Nebari docs currently doesn't feature a search bar for easy navigation across the docs. 

Add a search bar by going through various solutions available for Docusaurus to implement this feature.

**Comment by aktech** [comment]
Reopening this, as we still don't have it working. @HarshCasper are you still working on this?

**Comment by HarshCasper** [comment]
Hi @aktech — Sorry, didn't get to check on this. I will resume my work on this.

**Comment by aktech** [comment]
No worries, just checking in
