### ISSUE TITLE
[DOC] - Nebari getting started follow-up items

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docs#88]
Changes required, that will be addressed in separate issues:
- Add links to the `advanced-setting` section, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r906398850)
- Mention [`project naming conventions`](https://github.com/nebari-dev/nebari/pull/45#issuecomment-1165933587)
- Add Alt text and mouse over text to images, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907643807)
- Link to Keycloak docs for `root` management?, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907721910)
-  Add troubleshooting question for `Can't find my KUBECONFIG_FILE on /temp, what should I do?` ? [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907730148)
- Add more clinical presentation of the features present/absent in each cloud provider option, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907748222)
- Need to add a link here to the 'base costs' section of the docs. [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907762049)
- Need to add docs regarding `local` and `pre-existing` Kubernetes installation options, why use them, and what`s the difference? [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907767264)

_Originally posted by @viniciusdc in https://github.com/nebari-dev/nebari/issues/45#issuecomment-1171549318_

**Comment by trallard** [comment]
- [ ] Add links from the getting started to the How to guides https://www.nebari.dev/getting-started/installing-nebari - i.e. what are the next steps folks want to follow à-la https://www.gatsbyjs.com/docs/tutorial/part-0/#whats-coming-next
- [ ] @kcpevey will run through the installation herself to find more gotchas

**Comment by kcpevey** [comment]
* [ ]  Add links to the `advanced-setting` section, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r906398850)
  - https://github.com/nebari-dev/nebari-docs/issues/102
* [ ] Mention [`project naming conventions`](https://github.com/nebari-dev/nebari/pull/45#issuecomment-1165933587)
  - https://github.com/nebari-dev/nebari-docs/issues/103
* [ ] Add Alt text and mouse over text to images, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907643807)
  - https://github.com/nebari-dev/nebari-docs/issues/104
* [ ] Link to Keycloak docs for `root` management?, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907721910)
  - https://github.com/nebari-dev/nebari-docs/issues/105
* [ ]  Add troubleshooting question for `Can't find my KUBECONFIG_FILE on /temp, what should I do?` ? [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907730148)
  - https://github.com/nebari-dev/nebari-docs/issues/83#issuecomment-1171641391
* [ ] Add more clinical presentation of the features present/absent in each cloud provider option, [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907748222)
  - https://github.com/nebari-dev/nebari-docs/issues/106
* [ ] Need to add a link here to the 'base costs' section of the docs. [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907762049)
  - https://github.com/nebari-dev/nebari-docs/issues/107
* [ ] Need to add docs regarding `local` and `pre-existing` Kubernetes installation options, why use them, and what`s the difference? [ref.](https://github.com/nebari-dev/nebari/pull/45#discussion_r907767264)
  - https://github.com/nebari-dev/nebari-docs/issues/108

**Comment by viniciusdc** [comment]
Working on this, will open a PR for discussion later today

**Comment by trallard** [comment]
What is the status of this and the subtasks @kcpevey and @viniciusdc ?

**Comment by pavithraes** [comment]
This issue has been open for a while, so I'll close and prioritize the individually scoped issues separately. Please feel free to re-open if there is a need. :)
